apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: service-lookup-test
servers: 1
agents: 0
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server
        nodeFilters:
          - server:*
